
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1ESXhOREEwTVRrd01Wb1hEVE15TURJeE1qQTBNVGt3TVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGxuClJTRDROMlluVnFrTExKeEdHdGtrQ1k3ejJtUERMd2pwamlHckZ5SkdUOE5iTGtveEZiL0FMRS9Sb25RNDdJQ0EKdkpIRVZjUURUa1R4Wkk5aldyYzhnWHVpVUdZekVWaGIyNHZQcUFUYmZ2enJ4N0Y5ZDlGczVpTXEvYmNIUlprbgpPMjlOU2Q5a2xaa0RyNU1PQVRJMExKeE15YjU3VFFqSnNCN1pHeldIMzMrMFBFckNZQnd2QTVCbHVSbFFhczVRClQrQllJVWF0NzRQZDJZZlA4VlVVRkFMRndMRmhSQ3ppbjRLdnA5Z21EOHRpZVBkWGtBT1g5am5HZjhpaUozcUwKbWJYRzBWcDdoSEhRVTI2Tkg5TkdiQnNwY2pjT0JxZUMxa29SbC8wNzZ0VmNESEJtVEZDM3FZWFhLakpidm0yQQp6anNzMko3bEJ3QVl3cUZ5TnJVQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZDMXhIaEdUdzJJcHhHWjNISi93K2ZMeUZMSjJNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQkF3b3lYbk9lQTZUUjJLWnp2MgpmVWcrbzd4bTlrdFV4NHdBSE1meWRmUVJESHd4SHRUdHVRdktOU004QkJFUjF1Z1hIR0tvZWxITjNJdHVaVzJRCkQ5Nlp1dzdIV0t6anRpL0I5a3psTnNsVUdja3Z3QTUwMExXT2llVTROa0FmbHRpWVNYbm9CQ1Y1M3Fwcjk0dHIKaENNbkhyMFNqdGFKc0tranVkb2VaOXFKS2NpSUV1UU1lTnBYalZvQkRySXFZWWJ4MGRFYkVBOEJzd29VbGlRVgpvUnhiYjgza2c2NUNZVjMwMlBIeWFMWTk5b0FXVjE1SHN3ZnduSTh4VWNBNG5LYllTVjMwdHFrZ0RqWE93dXZGClR1QUJUbERuSllIWTE0WlNjam5zWmo4UkZaQ3dibkV2Mnc5eXBTT1pINEtKR2t2ZEY5dkhWWnZGd25BUm1QN3gKdmRVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://5e5b6b98-c4e6-4db8-a799-c9466b80d883.ap-south-1.linodelke.net:443
  name: lke52466

users:
- name: lke52466-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkFYN2RLNk9FUkV6anVnR2lxUmoyejFPM28taXNORHRMWktPTnY5MFBLdFkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tMnYyY3giLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiOTExOTFhYjItOGFhOC00MDI5LThiMWYtYmZkMjVjMmZmMGEwIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.R_WzqoUbwxNXhhRNWSE43vwFGig3OT9QeAjWttlvUZQDbuui0mWu8GY6VxMJLz3nc7b3mO4FcCcnekfVGikDMNLSTY1UjvxcX4KZ0QGTgoWdr2d865vBwHpF1eoZfnDzjUZKrr6Y-cTIEqKbaMxVeNgKW9wf2H--8qT94HbU1SQidxpRJGKPdDZWSI0Ioec38ZzxcRvJwkDRVmuq2a2q7-9UP70G7jkWZLBA5qtFrRINWtAe_X7Rqjtxvm8Il9KyFaFArPgqKu3MUoF7DVyzACRUZY32kd-rXoZukVjtlrk4X7Xk2J7kxmD0QCHQQ630eJ87vZAZMU6yPggD5KpZ9w

contexts:
- context:
    cluster: lke52466
    namespace: default
    user: lke52466-admin
  name: lke52466-ctx

current-context: lke52466-ctx
